sudo: required
services:
  - docker

before_install:
  - docker build -t nbnodejs/frontend-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nbnodejs/frontend-react npm run test -- --coverage

